/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NhanVien.QRCode;

import NhanVien.entity.NhanVien;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.logging.Level;

import org.apache.log4j.Logger;

/**
 *
 * @author NguyenVanKien
 */
public class WebCam extends javax.swing.JFrame implements Runnable, ThreadFactory {

    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private Executor executor = Executors.newSingleThreadExecutor(this);

    private IDListener listener;

    public interface IDListener {

        void onIDReceived(String qrCodeString);
    }

    public void addIDListener(IDListener listener) {
        this.listener = listener;
    }

    /**
     * Creates new form WebCam
     */
    public WebCam() {
        initComponents();
        initWebcam();

        setLocationRelativeTo(null); //
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebCam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebCam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebCam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebCam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebCam().setVisible(true);
            }
        });
    }

    private void initWebcam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        jPanel2.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 300));

        executor.execute(this);
    }

    @Override
    public void run() {
        do {

            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
            Result result = null;
            BufferedImage image = null;
            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }
            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException ex) {
                
            }

            if (result != null) {
                closeWindowAndWebcam();
                
                
                
    
                
                
                
                
                
                if (listener != null ) {
                    
                    
                    
                    String qrCodeString = result.getText();
                    
                    
//                    NhanVien nv=parseCCCDInfo(qrCodeString);
                
                
//                int startIndex = cccd.indexOf("CCCD: ");
//        
//        // Kiểm tra xem chuỗi "CCCD: " có tồn tại trong chuỗi mã QR không
//        if (startIndex != -1) {
//            // Trích xuất số CCCD từ chuỗi mã QR
//            String cccd2 = cccd.substring(startIndex + 6); // 6 là độ dài của chuỗi "CCCD: "
//            // Hiển thị số CCCD
//            //System.out.println("Số CCCD: " + cccd);
//            
            listener.onIDReceived(qrCodeString);
                    webcam.close();
                    dispose();
//            
//        } else {
//            System.out.println("Không tìm thấy thông tin CCCD trong mã QR.");
//        }
//                    
//                }
//            
            }
            }
        } while (true);
    }
        
    
//    private static String extractValue(String qrCodeString, String keyword) {
//        // Tìm vị trí của từ khóa trong chuỗi mã QR
//        int startIndex = qrCodeString.indexOf(keyword + ": ");
//        
//        // Kiểm tra xem từ khóa có tồn tại trong chuỗi mã QR không
//        if (startIndex != -1) {
//            // Tìm vị trí kết thúc của thông tin
//            int endIndex = qrCodeString.indexOf(";", startIndex);
//            if (endIndex == -1) {
//                endIndex = qrCodeString.length(); // Nếu không tìm thấy dấu chấm phẩy, lấy toàn bộ chuỗi từ vị trí startIndex
//            }
//            // Trích xuất và trả về giá trị từ chuỗi mã QR
//            return qrCodeString.substring(startIndex + keyword.length() + 2, endIndex);
//        } else {
//            return null; // Trả về null nếu không tìm thấy thông tin
//        }
//    }
//    
//    private static NhanVien parseCCCDInfo(String qrCodeString) {
//        // Phân tích chuỗi mã QR và trích xuất các thông tin cần thiết
//        // Ví dụ: Sử dụng các phương thức xử lý chuỗi để trích xuất các thông tin từ chuỗi mã QR
//
//        // Giả sử các thông tin được trích xuất từ chuỗi mã QR
//        String name = extractValue(qrCodeString, "Name");
//        String dob = extractValue(qrCodeString, "DOB");
//        String address = extractValue(qrCodeString, "Address");
//        String cccd = extractValue(qrCodeString, "CCCD");
//
//        // Tạo một đối tượng CCCDInfo và trả về
//        return new NhanVien(name, cccd, name, ngaySinh, cccd, address, name, dob, name, true, createdAt, cccd, updatedAt, address, name, cccd);
//    }
    

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }
    
    public void onWindowClosing() {
        if (webcam != null && webcam.isOpen()) {
            webcam.close();
        }
    }
    
    
    public void closeWindowAndWebcam() {
        webcam.close();
        setVisible(false);
        dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
